excerpt_separator: ""
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
url: http://pkritiotis.github.io
title: Code Decoded
tagline: Software bits and pieces
description: Software bits and pieces
paginate: 5
