excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://pkritiotis.github.io
title: in awe of code
tagline: Software bits and pieces
description: Software bits and pieces
paginate: 5
